### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ghost** [p0isonBR/Mail-Access#1]
I think the new commit broke the scrpit :(

Its missing Valid email Access . i used your first commit verison awhile ago so i had that output of Valid Access.
 and when i checked the output file from that with your new commit it missed 75% of them ,
so than i went back to firs commit and it shows 100% Full output valid mail

**Comment by p0isonBR** [comment]
Sorry bro! I was working offline, and "accidentally" commit.  Fixing now.
