### ISSUE TITLE
I dont know how to label thid isnt issue im sorry!

### ISSUE THREAD

**Issue by ghost** [p0isonBR/Mail-Access#2]
BRUH!!! thank you so much for fixing it and Giving me the one and only Mall Access Checker i use ! 

had to go back to a bleh one and i was missing hits :(

thanks for fixing it soo fastly working Perfectly AGAIN!!!! Truly so thankful for your mad scientist creation of a Script  ^-^

<3

**Comment by p0isonBR** [comment]
Thanks for reporting the issue! if you need help or suggestions, contact me on [Telegram](https://t.me/p0isonBR). Thx!
